# Generated by Django 4.0.5 on 2022-06-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeprod', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=8)),
                ('quantidade', models.CharField(max_length=5)),
            ],
        ),
    ]
